### ISSUE TITLE
ConsumeProduct ?

### ISSUE THREAD

**Issue by canado** [cranberrygame/cordova-plugin-payment-iap#12]
With Google Play Service, I would like to use a game currency.
So I create a ManagedProduct.

I can buy it, it works, but if I try to consume it, I have this error

Sku:my_product was not consumable

In google play services' documentation it says
https://developer.android.com/google/play/billing/api.html#consume

If you are using the Version 3 API, you can also consume managed items within your application.

Is cordova-plugin-payment-iap using Version 3 API ?
Is there something I need to do in In-app Product section of google Play Services ?
Or something else within the code ?

thanks

**Comment by jackdyson31** [comment]
Hi Canado,

Did you manage to find a way to sort this out ? If so would mind sharing ? I have the same problem.

J

**Comment by dariank38** [comment]
Hi, Canado
If you can, please share the solution to fix this issue.
I'm still having this error.

**Comment by canado** [comment]
Hello 

I had to do some troubleshoot to find out that my first buy was corrupted ( for unknown reasons), 
I would suggest to create other products and test them.
If you have well configured the plugin, it should work

**Comment by dariank38** [comment]
Thanks for your reply.

**Comment by canado** [comment]
Also for android, try a release alpha and on iOS try the testflight feature
